[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"

[env]
RAILWAY_DISABLE_CORS_OVERRIDE = "true"
RAILWAY_STATIC_URL = "false"
RAILWAY_DISABLE_CORS = "true"
RAILWAY_CORS_DISABLED = "true"
DISABLE_RAILWAY_CORS = "true"
CORS_ORIGIN = "https://www.trustelectonline.com,https://trustelectonline.com"
NODE_ENV = "production"
RAILWAY_ENVIRONMENT = "production"
RAILWAY_OVERRIDE_CORS = "false"

