[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"

[env]
RAILWAY_DISABLE_CORS_OVERRIDE = "true"
RAILWAY_STATIC_URL = "false"
CORS_ORIGIN = "https://www.trustelectonline.com,https://trustelectonline.com,https://trust-elect-qz9k-git-main-louie2312s-projects.vercel.app,https://trust-elect-jiq9-h8rxhtpx1-louie2312s-projects.vercel.app"
NODE_ENV = "production"
RAILWAY_ENVIRONMENT = "production"